### PR TITLE
Extract descriptions from libraries/*.rb

### PR DESCRIPTION
**Pull request by nvwls**

### CODE REVIEW

**Comment by realityforge** [comment]
This looks good .. 

Would you be interested in access to the github repository and ruby gems account so you could release it yourself?

**Comment by nvwls** [comment]
I could but I was wondering if you'd like to move it over to https://github.com/sous-chefs/ ?

**Comment by realityforge** [comment]
That would be fine as long as I still had access to the repository ;)

It looks like I can initiate a transfer locally and then it would be up to the organisation owner would need to approve and give me access again.

**Comment by realityforge** [comment]
Ok - I will poke around and see how to get it moved over there.

**Comment by realityforge** [comment]
Ok - it looks like there is a bit more effort to get involved over there than I can put in atm.

**Comment by realityforge** [comment]
Released as `0.29.0`

**Pull request merged**
