### PR TITLE
Adds Travis CI test support and badges

### PR DESCRIPTION
**Pull request by philoserf**
Introduces Travis CI testing support. The fixture directory holds a simple cookbook and a few test support files. The fixture cookbook needs further work to cover more scenarios and yet this seems like minimal viable product for Travis testing.

Also adds a set of badges for Build Status, Code Coverage, Gem version, Dependency Status, and Inline code documentation.

### CODE REVIEW

**Comment by philoserf** [comment]
This pull request introduces the Travis Ci testing mentioned in issue #15 and the test/support matrix mentioned in issue #17 .

**Comment by realityforge** [comment]
Thanks a lot for this!

**Comment by realityforge** [comment]
I am away traveling but will try to release this in a couple of weeks when I get back. Thanks again!

**Comment by realityforge** [comment]
Released 0.16.0 - thanks again for the changes

**Pull request merged**
