### PR TITLE
Add chef_versions support

### PR DESCRIPTION
**Pull request by Nklya**
Hello.

Thank you for this project! It's very convenient to generate documentation automatically.

With this PR I would like to add support of chef_versions from metadata.rb.
I tested this feature and I hope it will be merged so everyone can be able to use it.

### CODE REVIEW

**Comment by realityforge** [comment]
This looks like a neat feature but it does not seem to be backwards compatible with earlier versions of chef that did not support that metadata. You can see the problem in the TravisCI failures ;)

Would you mind making it conditional on the presence of metadata. Probably guarding it via `if @metadata.methods.include? : chef_versions`. Thanks!

**Comment by Nklya** [comment]
Thanks Peter!

I will try to implement it this week.

**Comment by Nklya** [comment]
@realityforge Peter, I committed the fix, please review)

**Comment by realityforge** [comment]
Thanks for the fix. Change merged, recorded, tagged and released as version `0.24.2`.

Thangs again and holler if you need anything else.

**Comment by Nklya** [comment]
Thanks!

**Comment by realityforge** [comment]
Grr - it seems I had missed recording `0.25.0` in the changelog which led to the kerfuffle. Oka doing a new release as `0.25.2` ... done.

Thanks for the heads up!

**Pull request merged**
