### PR TITLE
If `Berksfile` exists, add source_url links to cookbooks

### PR DESCRIPTION
**Pull request by nvwls**

### CODE REVIEW

**Comment by nvwls** [comment]
Could you please release a new version to rubygems.org? Thanks!

**Comment by realityforge** [comment]
Version `0.28.0` pushed. Enjoy!

**Comment by nvwls** [comment]
Still not seeing it on https://rubygems.org/gems/knife-cookbook-doc

**Comment by realityforge** [comment]
Hmm ... it seems something went wrong with the script. I will repush .... done.

HTH

**Pull request merged**
