### PR TITLE
Remove /m from regex

### PR DESCRIPTION
**Pull request by dblessing**
The new regex along with /m on the resource comments was flaky. Can you think of a reason the /m would be necessary now? I tested every combination of comments and multiline attribute definitions and this seems to work as expected.

AFAICT this complies with the comment syntax documentation in the README.

### CODE REVIEW

**Comment by realityforge** [comment]
Merged this commit, rand the gem against some of our more complex cookbooks and it produced identical code so  performed another release (Version 0.14.0).

Thanks again!

**Comment by dblessing** [comment]
Thanks so much. Hopefully this is the last PR for this functionality ;)

**Comment by realityforge** [comment]
:)

**Comment by dblessing** [comment]
Did the cookbook you tested have all types of comments? Now both type of multiline comments aren't working for me. I'm absolutely at a loss...this PR represents the *exact* working copy I had just 2 days ago. Now, I install the gem and this patch breaks multiline comments but singles are fine. :disappointed:

**Comment by realityforge** [comment]
Turns out that they were all single line ;)

**Pull request merged**
